-- Write a query to display the first name, last name, and email address of
-- employees hired from January 1, 2003, to December 31, 2012. Sort the output
-- by last name and then by first name. (Problem 7.46)
