-- Write a query to display the employee number, last name, first name, salary
-- "from" date, salary end date, and salary amount for employees 83731, 83745,
-- and 84039. Sort the output by employee number and salary "from" date.
-- (Problem 7.48)

SELECT LGSALARY_HISTORY.EMP_NUM, LGEMPLOYEE.EMP_LNAME, LGEMPLOYEE.EMP_FNAME, LGSALARY_HISTORY.SAL_FROM, LGSALARY_HISTORY.SAL_END, LGSALARY_HISTORY.SAL_AMOUNT
FROM LGEMPLOYEE, LGSALARY_HISTORY
WHERE LGEMPLOYEE.EMP_NUM = LGSALARY_HISTORY.EMP_NUM
AND LGSALARY_HISTORY.EMP_NUM = 83731
OR LGSALARY_HISTORY.EMP_NUM = 83745
OR LGSALARY_HISTORY.EMP_NUM = 84039;