-- Write a query to display the employee number, last name, first name, and sum
-- of invoice totals for all employees who completed an invoice. Sort the
-- output by employee last name and then by first name. (Problem 7.61)
