-- Write a query to display the customer code, first name, and last name of all
-- customers who have had at least one invoice completed by employee 83649 and
-- at least one invoice completed by employee 83677. Sort the output by
-- customer last name and then first name. (Problem 8.24)
