-- The purchasing manager is still concerned about the impact of price on
-- sales. Write a query to display the brand name, brand type, product SKU,
-- product description, and price of any products that are not a premium brand,
-- but that cost more than the most expensive premium brand products. (Problem
-- 8.27)
